# Generated by Django 4.0.2 on 2022-03-15 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='des',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
